Feat/Employee Routes & Employee Controller
Property-Search-Engine/admin-server pull request #33
Opened 2021-02-03 20:40 UTC by devmxhv

Implemented Employee Routes and Controller with their respective tests.

2021-02-03 20:55 UTC, JasterV requested changes
Mola! Te ha quedado muy limpio :D Hago request de algunos cambios por ficheros que he quitado en mi pr

2021-02-03 20:55 UTC, JasterV commented on docker-compose-test.yaml
> +            - "5000:5000"
```suggestion
            - 5000:5000
```

2021-02-03 20:55 UTC, JasterV commented on src/controllers/__tests__/filters.test.js
> +});
Este fichero lo he borrado, puedes borrarlo tambien :p

2021-02-03 20:55 UTC, JasterV commented on src/controllers/__tests__/property-controller.test.js
> +    })
He borrado la carpeta de controllers/__tests__ despues de implementar validacion por joi

2021-02-03 20:55 UTC, JasterV commented on src/controllers/user-controller.js
>      }
Al ser la de register, quizás devolveria un error diciendo que el usuario ya está registrado

2021-02-03 20:55 UTC, JasterV commented on Makefile
> +	docker-compose -f docker-compose-test.yaml up -d --scale node=0 && docker-compose -f docker-compose-test.yaml -p 5000:5000 run node /bin/sh
```suggestion
up_forward: down
	docker-compose -f docker-compose-test.yaml up -d --scale node=0 && docker-compose -f docker-compose-test.yaml -p 5000:5000 run node /bin/sh
```

2021-02-03 20:55 UTC, JasterV commented on src/models/schemas/property-min.js
> +module.exports = { PropertyMinSchema, HomeMinSchema }
Elimina este fichero tambien :p

2021-02-04 10:38 UTC, devmxhv commented on src/controllers/user-controller.js
>      }
No porque tambien hace de enpoint para la funcion syncdata del  client

2021-02-04 11:38 UTC, merged